### ISSUE TITLE
Orthorectified and ROI

### ISSUE THREAD

**Issue by winkmike** [centreborelli/s2p#162]
Hi,

Thanks for the great work! I have two questions about the s2p pipeline: 

1. Does s2p expect the satellite images to be orthorectified? 
2. From what I understand, specifying ROI is a way to "mask out" unrelated parts we do not want to reconstruct. Since only 1 ROI is specified in the sample `config.json`, does s2p assume that both images have the same orientation and cover the same area? Is there a way to specify different ROI for each image? My two images cover slightly different areas, but the parts I want to reconstruct lie inside the overlapping region.

**Comment by gfacciol** [comment]
Hi, - s2p uses non orthorectified images. Orthorectified images lack the projection functions needed to trace link points in 3d space and their projection  in the image. These parameters are usually stored within the geotiff product- the roi specifies the area of interest (in geographic coordinates ) to be reconstructed. S2p will only reconstruct that area. Don’t align the images. Even if the images are flipped, the projection functions encode that transformation.On 20 Dec 2024, at 09:37, winkmike ***@***.***> wrote:﻿
Hi,
Thanks for the great work! I have two questions about the s2p pipeline:

Does s2p expect the satellite images to be orthorectified?
From what I understand, specifying ROI is a way to "mask out" unrelated parts we do not want to reconstruct. Since only 1 ROI is specified in the sample config.json, does s2p assume that both images have the same orientation and cover the same area? Is there a way to specify different ROI for each image? My images cover slightly different areas, but the parts I want to reconstruct lie inside the overlapping region.

**Comment by winkmike** [comment]
Thanks for the clarifications, it helps!
